name: test

on:
  push:
    branches:
      - feature

permissions:
  id-token: write
  contents: read

jobs:
  myjob:
    name: deployment to staging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
         uses: actions/checkout@v4

      - name: Azure Login
         uses: Azure/login@v2.3.0
        with:
          client-id: c4df3811-9daa-4848-b9e0-4cd8bacc17f2
          tenant-id: 749c1dd0-8da4-446d-987c-6deb1b6cbab9
          subscription-id: 879e262b-becf-4bea-a163-835b023ba8e0
          enable-AzPSSession: true
          environment: azurecloud
          client-secret: 36a474be-8e3b-460a-9ece-d0669a362fed
          auth-type: SERVICE_PRINCIPAL

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest
